package com.mockaroo.api.interfaces;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.HttpURLConnection;

/**
 * Interface that provide base methods to open connection to Mockaroo site
 * @author Dennis Hernández Vargas
 * @version 0.1.0
 * @since 09/July/2014
 */
public interface IMockarooUrl {

	static final String urlMockaroo = "http://www.mockaroo.com/api/generate.json?key=";
	
	/**
	 * Open a connection with Mackroo
	 * @param papiKey Api key generated by Mackroo
	 * @return Connection
	 * @throws MalformedURLException
	 * @throws Exception
	 * @throws IOException
	 */
	HttpURLConnection openConnecion() throws MalformedURLException, Exception, IOException;
}
