package com.mockaroo.api.interfaces;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.HttpURLConnection;

public interface IUrl {

	static final String urlMockaroo = "http://www.mockaroo.com/api/generate.json?key=";
	
	/**
	 * Open a connection with Mackroo
	 * @param papiKey Api key generated by Mackroo
	 * @return Connection
	 * @throws MalformedURLException
	 * @throws Exception
	 * @throws IOException
	 */
	HttpURLConnection openConnecion(String papiKey, String pcontentType) 
			throws MalformedURLException, Exception, IOException;
}
