package com.mockaroo.api.enums;

/**
 * Enum that provide the mockaroo objects
 * @author Dennis Hernández Vargas
 * @version 0.1.0
 * @since 09/July/2014
 */
public enum MockarooType {
	Blank,
	Boolean,
	City,
	Color,
	Company_Name,
	Country,
	Credit_Card_1,//#
	Credit_Card_Type,
	Currency,
	Currency_Code,
	Custom_List,
	Date,
	Domain_Name,
	Email_Address,
	Encrypt,
	Family_Name_Chinese,//(Chinese)
	First_Name,
	First_Name_European,//(European)
	First_Name_Female,//(Female)
	First_Name_Male,//(Male)
	Formula,
	Frequency,
	Full_Name,
	Gender,
	Gender_abbrev,//(abbrev)
	Given_Name_Chinese,//(Chinese)
	GUID,
	Hex_Color,
	IP_Address_v4,
	IP_Address_v6,
	ISBN,
	JSON_Array,
	Language,
	Last_Name,
	Latitude,
	Longitude,
	MAC_Address,
	Money,
	My_List,
	Normal_Distribution,
	Number,
	Paragraphs,
	Password,
	Phone,
	Province,
	Province_abbrev,//(abbrev)
	Race,
	Regular_Expression,
	Row_Number,
	Sentences,
	Sequence,
	Shirt_Size,
	Short_Hex_Color,
	SSN,
	State,
	State_abbrev,//(abbrev)
	Street_Address,
	Street_Name,
	Street_Number,
	Street_Suffix,
	Suffix,
	Template,
	Time,
	Time_Zone,
	Title,
	Top_Level_Domain,
	URL,
	Username,
	Words,
	Zip	
}